[package]
name = "advent_of_code_2018"
version = "0.1.0"
authors = ["lukechampine <luke.champine@gmail.com>"]

[lib]
bench = false

[dependencies]
rust-crypto = "0.2.36"
aoc-runner = "0.1.0"
aoc-runner-derive = "0.1.0"
scan_fmt = "0.1.3"
